# -*- coding: utf-8 -*-
"""project.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPHdBnv_ax8Y2I7-b0c0mVFm_x86PEnq
"""

# ====== PulseGuard — Fixed final code ======
# If running in Colab/Jupyter, uncomment and run the install line once:
# !pip install gradio transformers qrcode[pil] --quiet
#pip install qrcode[pil]
import io
import time
import random
import qrcode

data = "AI Smart Hospital"

img = qrcode.make(data)

img.save("hospital_qr.png")

print("QR Code Generated Successfully")
from difflib import get_close_matches

import gradio as gr
from PIL import Image

# Optional QR library (handle missing gracefully)
try:
    import qrcode
    QRCODE_AVAILABLE = True
except Exception:
    qrcode = None
    QRCODE_AVAILABLE = False

# Optional transformers support (best-effort)
try:
    from transformers import pipeline
    TRANSFORMERS_AVAILABLE = True
except Exception:
    pipeline = None
    TRANSFORMERS_AVAILABLE = False

# -----------------------------
# Local Medicine DB (unchanged behavior)
# -----------------------------
MED_DB = {
    "Dolo 650": {
        "dosage": "650 mg every 6-8 hours (max 4 tablets / 24 hrs)",
        "indications": ["fever", "pain", "headache"],
        "contraindications": ["severe liver disease", "alcoholism"],
        "side_effects": ["nausea", "stomach upset", "liver damage if overdosed"],
        "usage": "Analgesic & antipyretic (symptomatic relief)",
        "alternative": "Paracetamol 500 mg",
        "note": "Take after meals; avoid alcohol"
    },
    "Paracetamol 500": {
        "dosage": "500 mg every 6-8 hours (max 4 tablets / 24 hrs)",
        "indications": ["fever", "pain", "headache"],
        "contraindications": ["severe liver disease", "alcoholism"],
        "side_effects": ["rare allergic reaction", "liver damage if overdosed"],
        "usage": "Analgesic & antipyretic",
        "alternative": "Dolo 650",
        "note": "Safe at recommended doses; avoid alcohol"
    },
    "Ibuprofen 400": {
        "dosage": "200-400 mg every 4-6 hours as needed (max 1200 mg OTC/day)",
        "indications": ["inflammation", "pain", "fever"],
        "contraindications": ["peptic ulcer", "severe kidney disease", "aspirin allergy"],
        "side_effects": ["stomach upset", "GI bleeding (rare)", "kidney risk"],
        "usage": "Anti-inflammatory & analgesic; take with food",
        "alternative": "Paracetamol/Acetaminophen",
        "note": "Avoid if kidney disease or active GI bleeding"
    }
}

LOWER_KEY_MAP = {k.lower(): k for k in MED_DB.keys()}

def best_med_match(user_med: str, cutoff=0.6):
    if not user_med or not user_med.strip():
        return None
    q = user_med.strip().lower()
    candidates = list(LOWER_KEY_MAP.keys())
    matches = get_close_matches(q, candidates, n=1, cutoff=cutoff)
    if matches:
        return LOWER_KEY_MAP[matches[0]]
    return None

def check_med_suitability(med_key: str, age: int, health_conditions: list, disease_to_treat: str):
    entry = MED_DB[med_key]
    indications = [i.lower() for i in entry.get("indications", [])]
    contraindications = [c.lower() for c in entry.get("contraindications", [])]
    disease_ok = False
    if disease_to_treat and disease_to_treat.strip():
        disease_ok = disease_to_treat.strip().lower() in indications
    reasons = []
    for hc in health_conditions:
        hc_l = hc.strip().lower()
        for contra in contraindications:
            if contra in hc_l or hc_l in contra:
                reasons.append(f"Contraindicated: {contra}")
    is_suitable = len(reasons) == 0
    return {"is_suitable": is_suitable, "treats_disease": disease_ok, "reasons": reasons}

def format_med_html_card(med_key: str, suitability: dict, disease_to_treat: str, user_input: str):
    e = MED_DB[med_key]
    treats = "Yes" if suitability["treats_disease"] else "No"
    suitable_flag = "✅ Suitable" if suitability["is_suitable"] else "⚠️ Not suitable"
    reasons_html = "<br>".join(suitability["reasons"]) if suitability["reasons"] else "—"
    html = f"""
    <div style="border-radius:12px;padding:12px;margin:8px 0;background:linear-gradient(90deg,#ffffff,#f2fbff);box-shadow:0 6px 18px rgba(10,20,40,0.06)">
      <div style="font-size:0.9em;color:#475569;margin-bottom:6px">You entered: <b>{user_input}</b></div>
      <h3 style="margin:4px 0;color:#0b66c3;">💊 {med_key}</h3>
      <b>Dosage:</b> {e['dosage']}<br>
      <b>Indications:</b> {', '.join(e['indications'])}<br>
      <b>Treats requested disease ({disease_to_treat or '—'}):</b> {treats}<br>
      <b>Suitability:</b> <span style="color:{'#0b8a3e' if suitability['is_suitable'] else '#c93b3b'}">{suitable_flag}</span><br>
      <b>Reasons:</b> {reasons_html}<br>
      <b>Side Effects:</b> {', '.join(e['side_effects'])}<br>
      <b>Usage:</b> {e['usage']}<br>
      <b>Alternative:</b> {e['alternative']}<br>
      <b>Note:</b> {e['note']}<br>
    </div>
    """
    return html

def medicine_checker(med_input: str, age: int, health_conditions: str, disease_to_treat: str):
    meds = [m.strip() for m in (med_input or "").split(",") if m.strip()]
    health_list = [h.strip() for h in (health_conditions or "").split(",") if h.strip()]
    disease_clean = disease_to_treat.strip().lower() if disease_to_treat else ""
    if not meds:
        return "<div class='card'>⚠️ Please enter at least one medicine.</div>"

    time.sleep(0.35)  # short UX delay
    cards = []
    for med in meds:
        match = best_med_match(med)
        if not match:
            cards.append(f"<div class='card'><b>{med}</b><br><span style='color:#c93b3b;'>Medicine not found in local DB. Try different spelling or ask AI Doctor.</span></div>")
            continue
        suitability = check_med_suitability(match, age or 0, health_list, disease_clean)
        card_html = format_med_html_card(match, suitability, disease_clean, med)
        cards.append(card_html)
    tip = random.choice([
        "Tip: For liver/kidney conditions, always check contraindications before taking analgesics.",
        "Tip: If you have multiple medicines, check interactions separately with a clinician."
    ])
    cards.append(f"<div style='color:#475569;font-style:italic;margin-top:6px'>{tip}</div>")
    return "<div>" + "".join(cards) + "</div>"

# -----------------------------
# Optional small model for chat (best-effort)
# -----------------------------
ai_pipe = None
if TRANSFORMERS_AVAILABLE:
    try:
        ai_pipe = pipeline("text-generation", model="gpt2", tokenizer="gpt2")
    except Exception:
        ai_pipe = None

# -----------------------------
# AI Doctor: strict structured single-paragraph templates
# -----------------------------
def ai_doctor_strict(user_text: str):
    t = (user_text or "").strip().lower()
    if "headache" in t:
        return ("Condition: The user is experiencing a headache. "
                "Recommendations: 1. Rest and relaxation. 2. Hydration. 3. Over-the-counter pain relievers such as ibuprofen or acetaminophen. "
                "Warnings: 1. If the headache persists or worsens, seek medical attention. 2. Avoid alcohol and caffeine, which can exacerbate headaches. "
                "Follow-up: 1. If the headache does not improve within a few days, schedule an appointment with a healthcare provider. 2. If the headache is accompanied by other symptoms such as fever, stiff neck, or confusion, seek immediate medical attention.")
    if "fever" in t:
        return ("Condition: The user has a fever. "
                "Recommendations: 1. Rest and fluids. 2. Paracetamol (acetaminophen) or ibuprofen as per dosing instructions for age. 3. Monitor temperature and hydration. "
                "Warnings: 1. Seek medical care if temperature is high (>39°C) or if the patient appears very unwell. 2. Avoid aspirin in children/teens. "
                "Follow-up: 1. Reassess after 24-48 hours or sooner if symptoms worsen. 2. Seek urgent care for breathing difficulty, severe lethargy, rash, or persistent vomiting.")
    if "cough" in t or "throat" in t or "sore throat" in t:
        return ("Condition: The user reports cough and/or sore throat. "
                "Recommendations: 1. Rest and stay hydrated. 2. Use warm fluids and throat lozenges. 3. Use OTC analgesics for pain/fever if appropriate. "
                "Warnings: 1. Seek medical care if breathing difficulty, high fever, or if cough produces blood. 2. Avoid antibiotics unless prescribed. "
                "Follow-up: 1. If cough lasts more than 7-10 days or worsens, consult a clinician. 2. Seek immediate care for severe breathlessness.")
    if "stomach" in t or "abdominal" in t or "nausea" in t or "vomit" in t:
        return ("Condition: The user has abdominal/stomach symptoms. "
                "Recommendations: 1. Rest, small sips of fluids, and bland diet. 2. Use anti-nausea measures as tolerated. 3. Avoid heavy/fatty meals until recovery. "
                "Warnings: 1. Seek urgent care if severe pain, blood in stool/vomit, persistent fever, or dehydration. 2. Avoid NSAIDs if ulcers or GI bleeding risk. "
                "Follow-up: 1. See a clinician if symptoms persist >48 hours or worsen. 2. Obtain immediate care for severe, escalating pain.")
    return ("Condition: General symptom query. "
            "Recommendations: 1. Rest and stay hydrated. 2. Use symptomatic OTC medicines as appropriate (e.g., paracetamol for fever). 3. Monitor your symptoms. "
            "Warnings: 1. If symptoms worsen, or if you have severe signs (difficulty breathing, chest pain, confusion, decreased urine), seek immediate medical attention. "
            "Follow-up: 1. Reassess after 24-72 hours. 2. Consult a healthcare provider for persistent or worsening symptoms.")

# -----------------------------
# AI Chat (short, human-friendly replies) - returns updated history only
# -----------------------------
def ai_chat_short(user_text: str, history):
    user_text = (user_text or "").strip()
    history = history or []
    if not user_text:
        return history

    t = user_text.lower()
    if "headache" in t:
        reply = "Likely tension or migraine. Rest, hydrate, and consider paracetamol or ibuprofen if suitable. See doctor if severe, persistent, or with fever/neurological signs."
    elif "fever" in t:
        reply = "Fever likely viral; rest, fluids, paracetamol for comfort. See doctor for high fever or severe symptoms."
    elif "cough" in t:
        reply = "Try rest, fluids, steam inhalation, and OTC meds for symptom relief. See doctor if breathing is difficult or persistent."
    else:
        if ai_pipe:
            try:
                out = ai_pipe(user_text, max_new_tokens=40, temperature=0.3)[0]["generated_text"]
                generated = out.replace(user_text, "").strip()
                reply = generated.split("\n")[0].strip() or "Sorry — couldn't create a concise answer; try rephrasing."
            except Exception:
                reply = "Rest, hydrate, and monitor. Consult a clinician if severe or worsening."
        else:
            reply = "Rest, hydrate, and monitor. Consult a clinician if severe or worsening."

    history.append((user_text, reply))
    return history

# -----------------------------
# QR generation helper
# -----------------------------
def generate_qr_image(link: str):
    link = (link or "").strip()
    if not link:
        return None, "Enter a valid Gradio share URL (e.g., https://xxxxx.gradio.live)."
    if not QRCODE_AVAILABLE:
        return None, "qrcode library not installed. Run: pip install qrcode[pil] and re-run."
    try:
        img = qrcode.make(link)
        bio = io.BytesIO()
        img.save(bio, format="PNG")
        bio.seek(0)
        return Image.open(bio), "QR generated. Right-click to save or use the Download button."
    except Exception as e:
        return None, f"QR generation error: {e}"

# -----------------------------
# Gradio UI (fixed: no .style(), correct outputs wiring)
# -----------------------------
CSS = """
body { font-family: Inter, Roboto, Arial, sans-serif; background: linear-gradient(135deg,#f6fbff,#ffffff); }
.card { background: linear-gradient(180deg,#ffffff,#fbfdff); border-radius:12px; padding:12px; box-shadow:0 6px 20px rgba(12,30,60,0.06); }
.small { color:#52606d }
"""

title_html = """
<div style="text-align:center;">
  <h1 style="margin:6px 0;color:#0b66c3;">PulseGuard — AI Prescription Guardian</h1>
  <div style="color:#475569;font-size:0.95em;">Medicine verification • Human-format AI Doctor • Simple AI chat</div>
</div>
"""

with gr.Blocks(css=CSS, title="PulseGuard — AI Prescription Guardian") as app:
    gr.HTML(title_html)

    with gr.Row():
        with gr.Column(scale=3):
            with gr.Tabs():
                with gr.TabItem("Medicine Checker"):
                    gr.Markdown("### Medicine Checker")
                    meds_text = gr.Textbox(label="Medicines (comma separated)", placeholder="e.g., Dolo 650, Ibuprofen 400")
                    age_box = gr.Number(label="Age", value=30)
                    health_box = gr.Textbox(label="Health conditions (comma separated)", placeholder="e.g., Liver disease")
                    disease_box = gr.Textbox(label="Disease to treat (primary)", placeholder="e.g., Fever")
                    check_btn = gr.Button("Verify Medicines")
                    result_html = gr.HTML()
                    check_btn.click(fn=medicine_checker, inputs=[meds_text, age_box, health_box, disease_box], outputs=[result_html])

                with gr.TabItem("AI Doctor (Structured)"):
                    gr.Markdown("### AI Doctor — returns single-paragraph structured clinical note.")
                    doc_in = gr.Textbox(label="Describe symptoms (e.g., 'I have a headache')", placeholder="Be concise — the AI Doctor will respond in a single structured paragraph.")
                    doc_btn = gr.Button("Get Doctor Note")
                    doc_out = gr.Textbox(label="Doctor's Note (structured)", lines=8)
                    doc_btn.click(fn=ai_doctor_strict, inputs=[doc_in], outputs=[doc_out])

                with gr.TabItem("AI Chat (Short replies)"):
                    gr.Markdown("### AI Chat — short, human-friendly answers with history (sidebar).")
                    chatbot = gr.Chatbot(label="Chat history", height=350)
                    chat_in = gr.Textbox(label="Ask a short question (e.g., 'Is Dolo 650 safe for liver disease?')", placeholder="Type and press Send")
                    send_btn = gr.Button("Send")
                    clear_btn = gr.Button("Clear History")
                    state = gr.State([])  # list of (user, bot)

                    def send_wrapper(u, history):
                        new_history = ai_chat_short(u, history)
                        # return outputs: chatbot (history list), clear input (""), state (history list)
                        return new_history, "", new_history

                    send_btn.click(fn=send_wrapper, inputs=[chat_in, state], outputs=[chatbot, chat_in, state])
                    clear_btn.click(lambda : ([], "", []), inputs=None, outputs=[chatbot, chat_in, state])

                with gr.TabItem("Share & QR"):
                    gr.Markdown("### Generate QR for judges\n1) Run the app with `share=True` to get a public link, or paste any public app URL below.\n2) Click Generate QR and download the PNG.")
                    share_link = gr.Textbox(label="Paste Gradio share link here", placeholder="https://xxxx.gradio.live")
                    qr_btn = gr.Button("Generate QR")
                    qr_img = gr.Image(type="pil", label="QR Code")
                    qr_status = gr.Textbox(label="Status", lines=2)
                    qr_btn.click(fn=generate_qr_image, inputs=[share_link], outputs=[qr_img, qr_status])

        with gr.Column(scale=1):
            gr.Markdown("### Quick Tips & Examples")
            gr.Markdown("- Medicine Checker examples: `Dolo 650`, `Paracetamol`.\n- AI Doctor examples: `I have a headache`, `I have fever and cough`.\n- AI Chat: short questions, e.g., `How to treat mild fever?`")
            gr.HTML("<div class='card small'>⚠️ For production/clinical use, validate all dosing and interactions with official sources. This tool provides decision support only.</div>")

    gr.Markdown("<div style='margin-top:8px;color:#7f8a93;font-size:0.9em'>Built for demo/judging: paste your Gradio share link into the QR tab to create a judge-scannable QR image.</div>")

# Launch the app. In Colab use app.launch(share=True) to get a public URL to paste into the QR generator.
app.launch()

chatbot = gr.Chatbot(height=400)   # just pass height directly
